
[font]
size = 29.0

[font.normal]
family = "firacode"
style = "regular"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8

[general]
import = [
    "~/.config/alacritty/theme.toml"
]

[terminal]

[terminal.shell]
program = "/bin/zsh"
