import = [
    "~/.config/alacritty/theme.toml"
]

[font]
size = 25.0

[font.normal]
family = "firacode"
style = "regular"

[env]
TERM = "xterm-256color"

[window]
opacity = 1.0

[shell]
program = "/bin/zsh"
