# XTerm's default colors

# Default colors
# [colors.primary]
# background = '#000000'
# foreground = '#ffffff'
#
# # Normal colors
# [colors.normal]
# black   = '#000000'
# red     = '#cd0000'
# green   = '#00cd00'
# yellow  = '#cdcd00'
# blue    = '#0000ee'
# magenta = '#cd00cd'
# cyan    = '#00cdcd'
# white   = '#e5e5e5'
#
# # Bright colors
# [colors.bright]
# black   = '#7f7f7f'
# red     = '#ff0000'
# green   = '#00ff00'
# yellow  = '#ffff00'
# blue    = '#5c5cff'
# magenta = '#ff00ff'
# cyan    = '#00ffff'
# white   = '#ffffff'

# Rose pine moon
[colors.primary]
foreground = "#e0def4"
background = "#191724"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[colors.search.matches]
foreground = "#908caa"
background = "#393552"

[colors.search.focused_match]
foreground = "#232136"
background = "#ea9a97"

[colors.hints.start]
foreground = "#908caa"
background = "#2a273f"

[colors.hints.end]
foreground = "#6e6a86"
background = "#2a273f"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#2a273f"

[colors.selection]
text = "#e0def4"
background = "#44415a"

[colors.normal]
black = "#393552"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#ea9d34"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#d7827e"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"

[colors.dim]
black = "#6e6a86"
red = "#eb6f92"
green = "#3e8fb0"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ea9a97"
white = "#e0def4"
